[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.8

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 10

[colors]
[colors.primary]
background = "#202020"
foreground = "#ddbbaa"

[cursor]
style = { shape = "Block", blinking = "On"}
blink_interval = 750
blink_timeout = 10

[mouse]
hide_when_typing = true

[terminal]
shell = "/bin/zsh"
