[colors]
background = #000000
background-alt = #2a2a2a
foreground = #ffffff
alert = #ff0000
disabled = #777777

magenta = #cc66ff
orange = #ffa500
blue = #00aaff
purple = #6600ff

[bar/top]
width = 100%
height = 24pt

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

padding-left = 1
padding-right = 1

module-margin = 1

font-0 = JetBrainsMonoNerdFont;1

modules-left = i3
modules-center = date
modules-right = systray airplane bluetooth network pulseaudio battery

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
fixed-center = true

[bar/bottom]
width = 20%
height = 42pt
offset-x = 40%
offset-y = 2%
radius = 22

background = ${colors.background-alt}
foreground = ${colors.foreground}

line-size = 3pt

padding-left = 1
padding-right = 1

module-margin = 1

font-0 = JetBrainsMonoNerdFont:size=24;4

modules-center = term firefox discord steam end

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
fixed-center = true

override-redirect = true
; wm-restack = i3

bottom = true

; === modules ===
include-file = settings.ini
