[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 10

[colors]
[colors.primary]
background = '#111318'
foreground = '#e2e2e9'

[colors.cursor]
text = '#e2e2e9'
cursor = '#c4c6d0' 

[cursor]
style = { shape = "Block", blinking = "On"}
blink_interval = 750
blink_timeout = 20

[mouse]
hide_when_typing = true
