# tmux config

# Change prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split window with Enter
bind-key Enter split-window -h

# Enable mouse mode
set -g mouse on
unbind -T copy-mode MouseDragEnd1Pane

# Disable status bar
set -g status off
