# tmux config

# Change prefix to Ctrl+a
unbind C-b
set -g prefix ²
bind ² send-prefix

# Mouse
set -g mouse on

# Status bar
set -g status off

set -g status-style bg=default
set -g status-fg default

# Toggle status bar
bind-key a set status

# Split window with Enter
bind-key Enter split-window -h

# Kill tmux server
unbind C-d
bind-key C-d kill-server
