# ========== Oh-my-zsh config ==========
export ZSH="$HOME/.oh-my-zsh"

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

plugins=(
    git
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# ========== opam config ==========
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
# [[ ! -r '/home/otto/.opam/opam-init/init.zsh' ]] || source '/home/otto/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null

# ========== Config ==========

# Loads
autoload -Uz vcs_info
autoload -Uz tetriscurses

# Exports
export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat --paging=always -p -lman'"

# Visuals
autoload -Uz add-zsh-hook
set_up_prompt() {
    . $HOME/.config/scripts/prompt.zsh &> /dev/null
}
add-zsh-hook precmd set_up_prompt

# Aliases
alias ls='lsd'
alias grep='grep --color=auto'
alias tree='lsd --tree'

alias pacman='pacman --color=auto'
alias la='lsd -A'
alias rf='rm -rf'
alias nv='nvim'

alias less='bat -p'
alias cat='bat --paging=never --style=plain'

# Binds
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[3~' delete-char

local func-fg() {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N func-fg
bindkey '^Z' func-fg

# Neovim
if [ -n "$NVIM" ]; then
    source $HOME/.config/nvim/zshrc
fi
