[colors]
background = #00000000
foreground = #ffffff
alert = #ff0000
disabled = #777777

[bar/top]
width = 100%
height = 22pt

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

padding-left = 1
padding-right = 1

module-margin = 1

font-0 = JetBrainsMonoNerdFont;1

modules-left = i3
modules-center = date
modules-right = systray airplane bluetooth network pulseaudio battery

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
fixed-center = true

[bar/bottom]
width = 100%
height = 18pt

background = ${colors.background}
foreground = ${colors.foreground}
 
line-size = 3pt

padding-left = 1
padding-right = 1

module-margin = 1

font-0 = JetBrainsMonoNerdFont;2

modules-left = power xkeyboard backlight aurhelper
modules-center = archlinux polywins
modules-right = cpu memory filesystem

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
fixed-center = true
bottom = true

; === modules ===
include-file = settings.ini
