If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-std=c99, -pedantic, -Wall, -Wextra, -Wvla]

---

If:
  PathMatch: .*\.cpp|.*\.cc|.*\.cxx
CompileFlags:
  Add: [-std=c++20, -Wall, -Wextra, -pedantic, -Wold-style-cast]
