# === Wallpaper ==
exec --no-startup-id "$HOME/.fehbg"

# === Borders ===
set $focused_color #ffbb88
set $unfocused_color #444444

# target title bg text indicator border
client.focused #abc7ff #111318 #e2e2e9 #abc7ff #abc7ff
client.focused_inactive #33353a #111318 #e2e2e9 #33353a #33353a
client.unfocused #33353a #111318 #e2e2e9 #33353a #33353a
client.urgent #ffb4ab #111318 #ffb4ab #33353a #ffb4ab
client.placeholder  #33353a #111318 #e2e2e9 #33353a #33353a

default_border pixel 1
default_floating_border none
for_window [ floating ] border none

# === Gaps ===
gaps outer 2
gaps inner 4

# === Floating windows ===
for_window [ title="Volume Control" ] floating enable
for_window [ title="Network Connections" ] floating enable
for_window [ title="Bluetooth Devices" ] floating enable
