[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.75

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 10

[colors]
[colors.primary]
background = "#110022"
foreground = "#ddbb88"

[cursor]
style = { shape = "Block", blinking = "On"}
blink_interval = 750
blink_timeout = 20

[mouse]
hide_when_typing = true

[keyboard]
[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "PageDown"
mods = "Control"

[terminal]
shell = "/bin/zsh"
