[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.7

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 10

[colors]
[colors.primary]
background = "#110022"
foreground = "#ffcc88"

[cursor]
style = { shape = "Block", blinking = "On"}
blink_interval = 750
blink_timeout = 20

[mouse]
hide_when_typing = true
