[window]
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 10

[colors]
[colors.primary]
background = "#000000"
foreground = "#88ff88"

[cursor]
style = { shape = "Underline", blinking = "Always"}
blink_interval = 700
