# === Airplane Mode ===
bindsym XF86RFKill exec notify-send "Airplane mode $(rfkill list | grep -q 'Soft blocked: yes' && echo on || echo off)"

# === Brightness ===
bindsym XF86MonBrightnessDown exec --no-startup-id "brightnessctl set 10%-"
bindsym XF86MonBrightnessUp exec --no-startup-id "brightnessctl set +10%"

# === Screenshot ===
bindsym Print exec --no-startup-id "maim $HOME/Pictures/screenshots/$(date +%F-%T).png"
bindsym Shift+Print exec --no-startup-id "maim -s $HOME/Pictures/screenshots/$(date +%F-%T).png"

# === Rofi ===
bindsym $mod+d exec --no-startup-id "rofi -show drun -config $HOME/.config/rofi/dmenu.rasi"

bindsym $mod+Shift+e exec --no-startup-id "$HOME/.config/rofi/power/start.sh"
bindsym $mod+Shift+l exec --no-startup-id "$HOME/.config/rofi/layout/start.sh"
bindsym $mod+Shift+n exec --no-startup-id "$HOME/.config/rofi/wifi/start.sh"
bindsym $mod+Shift+b exec --no-startup-id "$HOME/.config/rofi/bluetooth/start.sh"
bindsym $mod+Shift+t exec --no-startup-id "$HOME/.config/rofi/themes/start.sh"

bindsym $mod+Shift+w exec --no-startup-id "$HOME/.config/rofi/wallpapers/start.sh"
bindsym $mod+w exec --no-startup-id "$HOME/.config/rofi/wallpapers_animated/start.sh"

# === Other ===
bindsym $mod+i exec --no-startup-id "i3lock"

bindsym $mod+Shift+Return exec --no-startup-id "$HOME/.config/scripts/term.sh"

bindsym $mod+Shift+Tab "workspace prev"
bindsym $mod+Tab "workspace next"

bindsym $mod+Shift+f exec "firefox"
bindsym $mod+Shift+p exec "firefox --private-window"
