# === Airplane Mode ===
bindsym XF86RFKill exec notify-send "Airplane mode $(rfkill list | grep -q 'Soft blocked: yes' && echo on || echo off)"

# === Brightness ===
bindsym XF86MonBrightnessDown exec --no-startup-id "brightnessctl set 10%-"
bindsym XF86MonBrightnessUp exec --no-startup-id "brightnessctl set +10%"

# === Screenshot ===
bindsym Print exec --no-startup-id "maim -s $HOME/Pictures/screenshots/$(date +%F-%T).png"

# === Rofi ===
bindsym $mod+d exec --no-startup-id "rofi -show drun"

bindsym $mod+Shift+e exec --no-startup-id "$HOME/.config/rofi/scripts/power.sh"
bindsym $mod+l exec --no-startup-id "$HOME/.config/rofi/scripts/layout.sh"
bindsym $mod+n exec --no-startup-id "$HOME/.config/rofi/scripts/wifi.sh"
bindsym $mod+b exec --no-startup-id "$HOME/.config/rofi/scripts/bluetooth.sh"

bindsym $mod+w exec --no-startup-id "$HOME/.config/rofi/scripts/wallpaper.sh"
bindsym $mod+Shift+w exec --no-startup-id "$HOME/.config/rofi/wallpapers_animated/start.sh"

bindsym $mod+Shift+f exec "$HOME/.config/rofi/scripts/firefox.sh"

# === Other ===
bindsym $mod+i exec --no-startup-id "$HOME/.config/scripts/i3lock.sh"

bindsym $mod+Shift+Return exec --no-startup-id "$HOME/.config/scripts/term.sh"

bindsym $mod+Shift+Tab "workspace prev"
bindsym $mod+Tab "workspace next"
