# === Volume ===
bindsym F1 exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym F2 exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym F3 exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%

# === Brightness ===
bindsym F11 exec --no-startup-id brightnessctl set 10%-
bindsym F12 exec --no-startup-id brightnessctl set +10%

# === Screenshot ===
bindsym Print exec --no-startup-id maim $HOME/Pictures/srceenshots/$(date +%F-%T).png
bindsym Shift+Print exec --no-startup-id maim -s $HOME/Pictures/screenshots/$(date +%F-%T).png

# === Rofi ===
bindsym $mod+d exec --no-startup-id "rofi -show drun -config $HOME/.config/rofi/dmenu/config.rasi"

bindsym $mod+Shift+e exec "$HOME/.config/rofi/power/start.sh"

bindsym $mod+Shift+w exec --no-startup-id "$HOME/.config/rofi/wallpapers/start.sh"

# === Other ===
bindsym $mod+Shift+i exec --no-startup-id i3lock

bindsym $mod+Shift+f exec firefox
bindsym $mod+Shift+p exec firefox --private-window
