# === Fix firefox bugs ===
exec --no-startup-id dbus-update-activation-environment --all
exec --no-startup-id systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# === Lauchers ===
exec_always --no-startup-id "pulseaudio"
exec_always --no-startup-id "dunst -conf .config/dunst/dunstrc"
exec_always --no-startup-id "udiskie"
exec_always --no-startup-id "picom"
exec_always --no-startup-id "autotiling"

# === Disable touchsreec ===
exec_always --no-startup-id "xinput disable 'ELAN Touchscreen'"

# === Set cursors ===
exec_always --no-startup-id "xrdb -merge ~/.Xresources"
exec_always --no-startup-id "xsetroot -cursor_name left_ptr"

# === Scripts ===
exec --no-startup-id "$HOME/.config/scripts/battery.sh"

# === Polybar ===
exec --no-startup-id "polybar -c $HOME/.config/polybar/config.ini top"
exec --no-startup-id "polybar -c $HOME/.config/polybar/config.ini bottom"

# === Set Wallpaper ==
exec --no-startup-id "$HOME/.fehbg"
