exec_always --no-startup-id pulseaudio
exec_always --no-startup-id dunst -conf .config/dunst/dunstrc
exec_always --no-startup-id udiskie

exec_always --no-startup-id xrdb -merge ~/.Xresources
exec_always --no-startup-id xsetroot -cursor_name left_ptr

exec_always --no-startup-id picom
exec_always --no-startup-id autotiling

exec_always --no-startup-id $HOME/.config/scripts/battery.sh

exec --no-startup-id polybar -c $HOME/.config/polybar/panel.ini
exec --no-startup-id polybar -c $HOME/.config/polybar/dock.ini
