# === Wallpaper ==
exec_always --no-startup-id $HOME/.fehbg

# === Borders ===
client.focused #cccc66 #000000 #ffffff #cccc66 #cccc66
client.urgent #ff0000 #ff0000 #ffffff #ff0000 #ff0000

client.unfocused #666666 #666666 #666666 #666666 #666666
client.focused_inactive #666666 #666666 #666666 #666666 #666666

new_window pixel 3
new_float pixel 0

# === Gaps ===
gaps inner 12
gaps outer 8
smart_gaps off

# === Floating windows ===
for_window [ title="Volume Control" ] floating enable
for_window [ title="Network Connections" ] floating enable
for_window [ title="Bluetooth Devices" ] floating enable
