# === Wallpaper ==
exec --no-startup-id "$HOME/.fehbg"

# === Borders ===
set $focused_color #ffffff

client.focused $focused_color #000000 #ffffff $focused_color $focused_color
client.urgent #ff0000 #ff0000 #ffffff #ff0000 #ff0000

client.unfocused #00000000 #00000000 #00000000 #00000000 #00000000
client.focused_inactive #00000000 #00000000 #00000000 #00000000 #00000000

default_border pixel 1
default_floating_border none
for_window [ floating ] border none

smart_borders on

# === Gaps ===
gaps inner 8
gaps outer 4
#smart_gaps off

# === Floating windows ===
for_window [ title="Volume Control" ] floating enable
for_window [ title="Network Connections" ] floating enable
for_window [ title="Bluetooth Devices" ] floating enable
