# === Borders ===
set $focused_color #ec46b2
set $unfocused_color #54454e
set $urgent_color #ff1b00

# client.name title_borders title_background title_foreground bottom_border borders

client.focused #000000 $focused_color #000000 $focused_color $focused_color
client.urgent $urgent_color #000000 $urgent_color $urgent_color $urgent_color

client.unfocused $focused_color #000000 $focused_color $unfocused_color $unfocused_color
client.focused_inactive $focused_color #000000 $focused_color $unfocused_color $unfocused_color

default_border pixel 2
default_floating_border none

# smart_borders on

# === Gaps ===
gaps inner 8
gaps outer 4
gaps top 0
# smart_gaps on

# === Floating windows ===
for_window [ title="Volume Control" ] floating enable
for_window [ title="Network Connections" ] floating enable
for_window [ title="Bluetooth Devices" ] floating enable

# === Other ===
title_align center
