; ===== bar/bottom =====

[module/sep]
type = custom/text
label = │
label-foreground = ${colors.disabled}

[module/start]
type = custom/text
format = 
click-left = rofi -show drun -config $HOME/.config/rofi/dmenu.rasi

[module/search]
type = custom/text
label = "   Type here to search            "
label-background = ${colors.foreground}
label-foreground = ${colors.background}

[module/options1]
type = custom/text
format = "   󰛺"

[module/i3]
type = internal/i3

pin-workspaces = true
index-sort = true

ws-icon-0 = 1;%{F#0000ff}%{F-}
ws-icon-1 = 2;%{F#ffff00}%{F-}
ws-icon-2 = 3;%{F#eeeeee}%{F-}
ws-icon-3 = 4;%{F#aa66f0}%{F-}
ws-icon-4 = 5;%{F#ff7700}%{F-}
ws-icon-5 = 6;%{F#0088ff}%{F-}
ws-icon-6 = 7;%{F#008800}󱎏%{F-}
ws-icon-7 = 8;%{F#ff00ff}%{F-}
ws-icon-8 = 9;%{F#00ccff}%{F-}
ws-icon-9 = 10;%{F#bbbbbb}%{F-}
ws-icon-default = 

label-focused-font = 2
label-unfocused-font = 2
label-urgent-font = 2
label-visible-font = 2

label-focused = %icon%
label-focused-underline = ${colors.disabled}
label-focused-padding = 1

label-unfocused = %icon%
label-unfocused-padding = 1

label-urgent = %icon%
label-urgent-underline = ${colors.alert}
label-urgent-padding = 1

label-visible = %icon%
label-visible-padding = 1

[module/options2]
type = custom/text
format = "  "
click-left = $HOME/.config/rofi/themes/start.sh

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %d/%m/%Y

label = %date%

[module/network]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 1.5

format-connected = %{A1:$HOME/.config/rofi/wifi/start.sh:}󰘊%{A}
format-disconnected = %{A1:$HOME/.config/rofi/wifi/start.sh:}󰖪%{A}
format-packetloss = 

format-connected-foreground = ${colors.foreground-alt}
format-disconnected-foreground = ${colors.foreground-alt}
format-packetloss-foreground = ${colors.foreground-alt}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false

label-muted = 
label-volume = 

format-muted-foreground = ${colors.foreground-alt}
format-volume-foreground = ${colors.foreground-alt}

click-right = pavucontrol

[module/battery]
type = internal/battery
full-at = 95
low-at = 20

battery = BAT1
adapter = ADP1

poll-interval = 5

format-charging-foreground = ${colors.foreground-alt}
format-discharging-foreground = ${colors.foreground-alt}
format-full-foreground = ${colors.foreground-alt}
format-low-foreground = ${colors.foreground-alt}

format-charging = <label-charging>
format-discharging = <ramp-capacity>
format-full = <label-full>
format-low = <label-low>

label-charging = 
label-full = 󱐋
label-low = 

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

[module/notif]
type = custom/text
format = 󰆈
